use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/woodjobber/WJSpecs.git'

platform :ios, '10.0'

target 'WaterfallKit_Example' do
#  pod 'WaterfallKit', :path => '../'
  pod 'WaterfallKit', '~> 0.0.3'
  pod 'SnapKit'
end
